package com.va.requestmgmt;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(1cfe31f891dfbfa90ce64f40f1f0d2fb)
 */
@org.kie.api.definition.type.Label(value = "Patient")
public class patient extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Age")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Label(value = "appt request")
    @org.kie.api.definition.type.Position(value = 6)
    private com.va.requestmgmt.appreq apptreq;
    
    @org.kie.api.definition.type.Label(value = "Appt Type")
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.String appttype;
    
    @org.kie.api.definition.type.Label(value = "City")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Label(value = "Disabled?")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Boolean disabled;
    
    @org.kie.api.definition.type.Label(value = "First Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String fname;
    
    @org.kie.api.definition.type.Label(value = "Last Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String lname;
    
    @org.kie.api.definition.type.Label(value = "Preferred Date")
    @org.kie.api.definition.type.Position(value = 10)
    private java.util.Date prefdate;
    
    @org.kie.api.definition.type.Label(value = "2nd Preferred Date")
    @org.kie.api.definition.type.Position(value = 11)
    private java.util.Date prefdate2;
    
    @org.kie.api.definition.type.Label(value = "Special Attention?")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.Boolean special;
    
    @org.kie.api.definition.type.Label(value = "State")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Label(value = "Status")
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String status;

    public patient() {
    }

    public patient(java.lang.String lname, java.lang.String fname, java.lang.Integer age, java.lang.Boolean disabled, java.lang.String city, java.lang.String state, com.va.requestmgmt.appreq apptreq, java.lang.String status, java.lang.String appttype, java.lang.Boolean special, java.util.Date prefdate, java.util.Date prefdate2) {
        this.lname = lname;
        this.fname = fname;
        this.age = age;
        this.disabled = disabled;
        this.city = city;
        this.state = state;
        this.apptreq = apptreq;
        this.status = status;
        this.appttype = appttype;
        this.special = special;
        this.prefdate = prefdate;
        this.prefdate2 = prefdate2;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public com.va.requestmgmt.appreq getApptreq() {
        return this.apptreq;
    }

    public void setApptreq(com.va.requestmgmt.appreq apptreq) {
        this.apptreq = apptreq;
    }
    
    public java.lang.String getAppttype() {
        return this.appttype;
    }

    public void setAppttype(java.lang.String appttype) {
        this.appttype = appttype;
    }
    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.Boolean getDisabled() {
        return this.disabled;
    }

    public void setDisabled(java.lang.Boolean disabled) {
        this.disabled = disabled;
    }
    
    public java.lang.String getFname() {
        return this.fname;
    }

    public void setFname(java.lang.String fname) {
        this.fname = fname;
    }
    
    public java.lang.String getLname() {
        return this.lname;
    }

    public void setLname(java.lang.String lname) {
        this.lname = lname;
    }
    
    public java.util.Date getPrefdate() {
        return this.prefdate;
    }

    public void setPrefdate(java.util.Date prefdate) {
        this.prefdate = prefdate;
    }
    
    public java.util.Date getPrefdate2() {
        return this.prefdate2;
    }

    public void setPrefdate2(java.util.Date prefdate2) {
        this.prefdate2 = prefdate2;
    }
    
    public java.lang.Boolean getSpecial() {
        return this.special;
    }

    public void setSpecial(java.lang.Boolean special) {
        this.special = special;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }
}