package com.va.requestmgmt;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(685f789a102f55c3bef130eafa893c01)
 */
@org.kie.api.definition.type.Label(value = "Patient")
public class patient extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Age")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Label(value = "appt request")
    @org.kie.api.definition.type.Position(value = 6)
    private com.va.requestmgmt.appreq apptreq;
    
    @org.kie.api.definition.type.Label(value = "City")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Label(value = "Disabled?")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Boolean disabled;
    
    @org.kie.api.definition.type.Label(value = "First Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String fname;
    
    @org.kie.api.definition.type.Label(value = "Last Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String lname;
    
    @org.kie.api.definition.type.Label(value = "State")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String state;

    public patient() {
    }

    public patient(java.lang.String lname, java.lang.String fname, java.lang.Integer age, java.lang.Boolean disabled, java.lang.String city, java.lang.String state, com.va.requestmgmt.appreq apptreq) {
        this.lname = lname;
        this.fname = fname;
        this.age = age;
        this.disabled = disabled;
        this.city = city;
        this.state = state;
        this.apptreq = apptreq;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public com.va.requestmgmt.appreq getApptreq() {
        return this.apptreq;
    }

    public void setApptreq(com.va.requestmgmt.appreq apptreq) {
        this.apptreq = apptreq;
    }
    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.Boolean getDisabled() {
        return this.disabled;
    }

    public void setDisabled(java.lang.Boolean disabled) {
        this.disabled = disabled;
    }
    
    public java.lang.String getFname() {
        return this.fname;
    }

    public void setFname(java.lang.String fname) {
        this.fname = fname;
    }
    
    public java.lang.String getLname() {
        return this.lname;
    }

    public void setLname(java.lang.String lname) {
        this.lname = lname;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
}