package com.va.requestmgmt;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(af0b9550f5e08ddd3a1aaf7251fec023)
 */
@org.kie.api.definition.type.Label(value = "Patient")
public class patient  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Last Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String lname;

    public patient() {
    }

    public patient(java.lang.String lname) {
        this.lname = lname;
    }


    
    public java.lang.String getLname() {
        return this.lname;
    }

    public void setLname(java.lang.String lname) {
        this.lname = lname;
    }
}